### ISSUE TITLE
Looking into making script not rely on python and be pure bash

### ISSUE THREAD

**Issue by Stetsed** [bryanvaz/vfnet#5]
Hey,

I love the script as I want to have my TrueNAS scale VM's use a Virtual Function instead of going over the device because less overhead. The only problem is I don't want to clog up the machine so I will be making a pure bash(but simpler) version of this. If you wish I will return it in this issue to you incase you wanna do something with it.

**Comment by bryanvaz** [comment]
Have a look at the `vfup` script in the repo. It's an early version written only in bash with just the error checking and VF creation code. The idea was that the bash script would always underpin the architecture so it would be simple to debug, especially at boot time, while the python code would handle UX functions like formatting and aggregating data, as well as being more user-friendly with more stringent data validations (modelled on the UX for `ip`); which are elements that cause bash scripts to balloon well past the 300 line count.

Unfortunately, getting the deterministic MAC addresses to work in a secure way (in a method that would not allow reverse engineering of the host MAC address from the VF MAC address) meant that I needed access to crypto libraries that weren't available in bash. As a result the python component now sits at the center of the architecture; but `vfup` is still used at boot time to perform all the error checking and validation.

If you throw your bash script on github and link it here, happy to look at it. Long term (if ever) I'll probably rewrite everything in C++ so its using the kernel module APIs rather than sysfs and ditch the python dependency.
